In [1]:
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.cross_validation import train_test_split
from sklearn.cross_validation import KFold
import matplotlib.pyplot as plt
plt.style.use('bmh')
%matplotlib inline

In [2]:
train_raw = pd.read_csv('data_sets/train.csv')
train_raw.describe()

,ID,var3,var15,imp_ent_var16_ult1,imp_op_var39_comer_ult1,imp_op_var39_comer_ult3,imp_op_var40_comer_ult1,imp_op_var40_comer_ult3,imp_op_var40_efect_ult1,imp_op_var40_efect_ult3,...,saldo_medio_var33_hace2,saldo_medio_var33_hace3,saldo_medio_var33_ult1,saldo_medio_var33_ult3,saldo_medio_var44_hace2,saldo_medio_var44_hace3,saldo_medio_var44_ult1,saldo_medio_var44_ult3,var38,TARGET
count,76020.000000,76020.000000,76020.000000,76020.000000,76020.000000,76020.000000,76020.000000,76020.000000,76020.000000,76020.000000,...,76020.000000,76020.000000,76020.000000,76020.000000,76020.000000,76020.000000,76020.000000,76020.000000,76020.000000,76020.000000
mean,75964.050723,-1523.199277,33.212865,86.208265,72.363067,119.529632,3.559130,6.472698,0.412946,0.567352,...,7.935824,1.365146,12.215580,8.784074,31.505324,1.858575,76.026165,56.614351,117235.809430,0.039569
std,43781.947379,39033.462364,12.956486,1614.757313,339.315831,546.266294,93.155749,153.737066,30.604864,36.513513,...,455.887218,113.959637,783.207399,538.439211,2013.125393,147.786584,4040.337842,2852.579397,182664.598503,0.194945
min,1.000000,-999999.000000,5.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5163.750000,0.000000
25%,38104.750000,2.000000,23.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,67870.612500,0.000000
50%,76043.000000,2.000000,28.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,106409.160000,0.000000
75%,113748.750000,2.000000,40.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,118756.252500,0.000000
max,151838.000000,238.000000,105.000000,210000.000000,12888.030000,21024.810000,8237.820000,11073.570000,6600.000000,6600.000000,...,50003.880000,20385.720000,138831.630000,91778.730000,438329.220000,24650.010000,681462.900000,397884.300000,22034738.760000,1.000000

In [8]:
train_x = train_raw.drop(['TARGET'],axis=1)
train_y = train_raw['TARGET'].values
print train_x.shape
print train_y.shape

(76020, 370)
(76020,)

In [49]:
X_train, X_valid, Y_train, Y_valid = train_test_split(train_x, train_y, test_size=0.5, 
                                                      random_state=42)

In [63]:
clf = RandomForestClassifier(n_estimators=500)
clf.fit(X_train[['var3','imp_ent_var16_ult1']],Y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=500, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [64]:
predictions = clf.predict(X_valid[['var3','imp_ent_var16_ult1']])

In [65]:
print predictions.sum()
print Y_valid.sum()

25
1481

In [66]:
error = np.sum(predictions != Y_valid,dtype=float)/len(Y_valid)
print error

0.0395685345962

# Test Data!!!

In [22]:
test_raw = pd.read_csv('data_sets/test.csv')
test_raw.describe()

,ID,var3,var15,imp_ent_var16_ult1,imp_op_var39_comer_ult1,imp_op_var39_comer_ult3,imp_op_var40_comer_ult1,imp_op_var40_comer_ult3,imp_op_var40_efect_ult1,imp_op_var40_efect_ult3,...,saldo_medio_var29_ult3,saldo_medio_var33_hace2,saldo_medio_var33_hace3,saldo_medio_var33_ult1,saldo_medio_var33_ult3,saldo_medio_var44_hace2,saldo_medio_var44_hace3,saldo_medio_var44_ult1,saldo_medio_var44_ult3,var38
count,75818.000000,75818.000000,75818.000000,75818.000000,75818.000000,75818.000000,75818.000000,75818.000000,75818.000000,75818.000000,...,75818.000000,75818.000000,75818.000000,75818.000000,75818.000000,75818.000000,75818.000000,75818.000000,75818.000000,75818.000000
mean,75874.830581,-1579.955011,33.138832,83.164329,74.312894,123.136448,4.578517,7.666855,0.470645,0.672444,...,0.160595,12.438559,1.327408,17.469991,12.674349,63.597839,11.404505,95.973025,70.504319,117386.348875
std,43882.370827,39752.473358,12.932000,1694.873886,364.211245,606.431562,133.383326,239.701416,34.028605,42.336668,...,32.441677,958.651673,170.449935,1252.618781,895.165516,3754.668953,1061.858193,4658.871575,3318.527783,247938.372544
min,2.000000,-999999.000000,5.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,-0.600000,-0.600000,0.000000,0.000000,0.000000,0.000000,1202.730000
25%,37840.250000,2.000000,23.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,67549.612500
50%,75810.000000,2.000000,27.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,105764.265000
75%,113996.500000,2.000000,39.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,118315.905000
max,151837.000000,238.000000,105.000000,240000.000000,21093.960000,47943.960000,21093.960000,47943.960000,6600.000000,6600.000000,...,8030.160000,146605.320000,40080.600000,162355.800000,138054.960000,453893.400000,217762.230000,496198.080000,354260.730000,28894395.510000

In [21]:
clf = RandomForestClassifier(n_estimators=500)
clf.fit(train_x,train_y)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=500, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [23]:
test_predictions = clf.predict(test_raw)

In [28]:
np.savetxt('santander_RF_naive.csv',
           np.c_[test_raw['ID'],test_predictions],
           delimiter=',',
           header='ID,TARGET',
           fmt='%d',
           comments='')

In [37]:
train_x.mean().order()

var3                                -1523.199277
num_var46_0                             0.000000
ind_var2                                0.000000
num_var41                               0.000000
num_var27                               0.000000
num_var28                               0.000000
num_var28_0                             0.000000
num_var27_0                             0.000000
num_reemb_var33_hace3                   0.000000
ind_var46                               0.000000
ind_var46_0                             0.000000
ind_var41                               0.000000
ind_var27                               0.000000
ind_var28                               0.000000
ind_var28_0                             0.000000
ind_var27_0                             0.000000
num_var46                               0.000000
num_reemb_var13_hace3                   0.000000
ind_var2_0                              0.000000
saldo_var27                             0.000000
imp_trasp_var33_out_hace3               0.000000
imp_trasp_var17_out_hace3               0.000000
num_trasp_var33_out_hace3               0.000000
imp_reemb_var33_hace3                   0.000000
imp_reemb_var13_hace3                   0.000000
saldo_var28                             0.000000
num_var2_ult1                           0.000000
imp_amort_var34_hace3                   0.000000
num_var2_0_ult1                         0.000000
saldo_var2_ult1                         0.000000
                                      ...
saldo_var42                          7191.725395
saldo_var30                         13679.673658
ID                                  75964.050723
var38                              117235.809430
delta_imp_aport_var33_1y3          131544.330141
delta_num_aport_var33_1y3          131544.330196
delta_imp_reemb_var33_1y3          131544.330426
delta_imp_trasp_var33_out_1y3      131544.330426
delta_num_trasp_var33_out_1y3      131544.330426
delta_num_reemb_var33_1y3          131544.330426
delta_imp_amort_var18_1y3          263088.660852
delta_imp_amort_var34_1y3          263088.660852
delta_imp_trasp_var17_in_1y3       526177.321679
delta_num_trasp_var17_in_1y3       526177.321679
delta_num_trasp_var17_out_1y3      526177.321705
delta_imp_trasp_var17_out_1y3      526177.321705
delta_num_trasp_var33_in_1y3       657721.652052
delta_imp_trasp_var33_in_1y3       657721.652052
delta_num_reemb_var17_1y3         2630886.608511
delta_imp_reemb_var17_1y3         2630886.608511
delta_imp_reemb_var13_1y3         4998684.556196
delta_num_reemb_var13_1y3         4998684.556196
delta_imp_aport_var17_1y3         5130228.886430
delta_num_aport_var17_1y3         5130228.886433
delta_imp_venta_var44_1y3         5524861.877952
delta_num_venta_var44_1y3         5524861.877986
delta_imp_compra_var44_1y3        9208103.129717
delta_num_compra_var44_1y3        9208103.129768
delta_num_aport_var13_1y3        48671402.235690
delta_imp_aport_var13_1y3        48671402.235872
dtype: float64